name: QUndo
main: com.eci.quickundo.QUndo
version: 1.1
author: Eci
api-version: 1.16
commands:
  qundo:
    description: Quick Undo command
    usage: /qundo <set|remove|undo|redo>
  q:
    description: Quick Undo command
    usage: /q <set|remove|undo|redo>
